# 1. Base image
FROM eclipse-temurin:17-jdk-alpine

# 2. Çalışma dizini
WORKDIR /app

# 3. Jar dosyasını kopyala
COPY target/api-gateway-0.0.1-SNAPSHOT.jar app.jar

# 4. Jar çalıştır
ENTRYPOINT ["java","-jar","/app/app.jar"]